/* ============================================================================
   121_ENT_REPORTOS_MN_ME_ROLLBACK.sql
   Fin: Revertir el AJUSTE y restaurar estado anterior (layout V7.1 implicito):
        - BRONZE: eliminar TIPOTASAPREMIO, TIPOMODIFICACION, FECHA_INFO.
        - SILVER: re-agregar 13 cols V7.1, revertir TIPOTASAPREMIO a int,
                  eliminar TIPOMODIFICACION y FECHA_INFO.
        - Restaurar SP SILVER y ION originales.
   ============================================================================ */

/* ----------------------------------------------------------------------------
   00 - BRONZE.[LMDA].[FT_REPORTOS]: revertir columnas agregadas
   ---------------------------------------------------------------------------- */
USE [BRONZE];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_REPORTOS' AND COLUMN_NAME='TIPOTASAPREMIO')
    ALTER TABLE [LMDA].[FT_REPORTOS] DROP COLUMN [TIPOTASAPREMIO];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_REPORTOS' AND COLUMN_NAME='TIPOMODIFICACION')
    ALTER TABLE [LMDA].[FT_REPORTOS] DROP COLUMN [TIPOMODIFICACION];

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_REPORTOS' AND COLUMN_NAME='FECHA_INFO')
    ALTER TABLE [LMDA].[FT_REPORTOS] DROP COLUMN [FECHA_INFO];

PRINT '>> BRONZE.[LMDA].[FT_REPORTOS]: columnas V3 revertidas.';
GO

/* ----------------------------------------------------------------------------
   01 - SILVER.[RR].[121_ENT_REPORTOS_MN_ME]: revertir estructura
        a) Eliminar TIPOMODIFICACION y FECHA_INFO (agregadas en AJUSTE).
        b) Revertir TIPOTASAPREMIO: varchar(1) -> int NULL.
        c) Re-agregar las 13 columnas V7.1.
   ---------------------------------------------------------------------------- */
USE [SILVER];
GO

-- a) Eliminar TIPOMODIFICACION
DECLARE @sqltm NVARCHAR(MAX) = '';
SELECT @sqltm = 'ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] DROP CONSTRAINT ' + dc.name
FROM sys.default_constraints dc
JOIN sys.columns col ON col.default_object_id = dc.object_id
JOIN sys.objects o   ON o.object_id = dc.parent_object_id
WHERE o.name='121_ENT_REPORTOS_MN_ME' AND col.name='TIPOMODIFICACION';
IF LEN(@sqltm) > 0 EXEC sp_executesql @sqltm;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='TIPOMODIFICACION')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] DROP COLUMN [TIPOMODIFICACION];
GO

-- Eliminar FECHA_INFO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='FECHA_INFO')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] DROP COLUMN [FECHA_INFO];
GO

-- b) Revertir TIPOTASAPREMIO: varchar(1) -> int NULL
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME'
             AND COLUMN_NAME='TIPOTASAPREMIO' AND DATA_TYPE='varchar')
BEGIN
    DECLARE @sqlrtt NVARCHAR(MAX) = '';
    SELECT @sqlrtt = 'ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] DROP CONSTRAINT ' + dc.name
    FROM sys.default_constraints dc
    JOIN sys.columns col ON col.default_object_id = dc.object_id
    JOIN sys.objects o   ON o.object_id = dc.parent_object_id
    WHERE o.name='121_ENT_REPORTOS_MN_ME' AND col.name='TIPOTASAPREMIO';
    IF LEN(@sqlrtt) > 0 EXEC sp_executesql @sqlrtt;

    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ALTER COLUMN [TIPOTASAPREMIO] int NULL;
    PRINT '>> TIPOTASAPREMIO revertido a int NULL.';
END
ELSE
    PRINT '>> TIPOTASAPREMIO: ya es int o no requiere cambio.';
GO

-- c) Re-agregar 13 columnas V7.1 (con DEFAULT para datos existentes)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='RESIDENCIA_CONTRAPARTE')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [RESIDENCIA_CONTRAPARTE] varchar(3) NOT NULL CONSTRAINT DF_121_RB_RESID DEFAULT ('');

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='PROPIA_TERCEROS')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [PROPIA_TERCEROS] varchar(1) NOT NULL CONSTRAINT DF_121_RB_PROPIA DEFAULT ('');

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='CLIENTE_PROV')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [CLIENTE_PROV] varchar(6) NOT NULL CONSTRAINT DF_121_RB_CLIPROV DEFAULT ('');

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='HAIRCUT')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [HAIRCUT] numeric(4,2) NOT NULL CONSTRAINT DF_121_RB_HAIRCUT DEFAULT (0);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='REP_SUSTITUCION')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [REP_SUSTITUCION] varchar(1) NOT NULL CONSTRAINT DF_121_RB_REPSUST DEFAULT ('');

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='MODALIDAD_REPORTO')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [MODALIDAD_REPORTO] varchar(2) NOT NULL CONSTRAINT DF_121_RB_MODAL DEFAULT ('');

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='PLAZO_EVERGREEN')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [PLAZO_EVERGREEN] numeric(3,0) NOT NULL CONSTRAINT DF_121_RB_PLAZO DEFAULT (0);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='REP_CONJUNTO_VAL')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [REP_CONJUNTO_VAL] varchar(1) NOT NULL CONSTRAINT DF_121_RB_REPCONJ DEFAULT ('');

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='REP_AG_TRIPARTITO')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [REP_AG_TRIPARTITO] varchar(1) NOT NULL CONSTRAINT DF_121_RB_REPAGTRI DEFAULT ('');

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='AGENTE_TRIPARTITO')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [AGENTE_TRIPARTITO] varchar(6) NOT NULL CONSTRAINT DF_121_RB_AGTRI DEFAULT ('');

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='TASA_REFERENCIA_PREMIO')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [TASA_REFERENCIA_PREMIO] numeric(3,0) NOT NULL CONSTRAINT DF_121_RB_TASAREF DEFAULT (0);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='SOBRETASA_PREMIO')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [SOBRETASA_PREMIO] numeric(8,4) NOT NULL CONSTRAINT DF_121_RB_SOBRETAS DEFAULT (0);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='121_ENT_REPORTOS_MN_ME' AND COLUMN_NAME='PERIODO_PAGO_PREMIO')
    ALTER TABLE [RR].[121_ENT_REPORTOS_MN_ME] ADD [PERIODO_PAGO_PREMIO] numeric(6,0) NOT NULL CONSTRAINT DF_121_RB_PERIODO DEFAULT (0);

PRINT '>> 13 columnas V7.1 restauradas en SILVER.[RR].[121_ENT_REPORTOS_MN_ME].';
GO

/* ----------------------------------------------------------------------------
   02 - SILVER SP: restaurar original (con cols V7.1, filtro FECHACONCERTACION)
   ---------------------------------------------------------------------------- */
USE [SILVER];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [dbo].[121_ENT_REPORTOS_MN_ME]
    @CorreoNotificacion NVARCHAR(255) = NULL,
    @PerfilCorreo       NVARCHAR(255) = NULL,
    @ProgramadorJob     NVARCHAR(128) = NULL,
    @FechaSistema       DATETIME
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @MensajeError   NVARCHAR(MAX) = '';
    DECLARE @ExitoEjecucion BIT           = 1;
    DECLARE @FilasInsertadas INT          = 0;
    DECLARE @FilasEliminadas INT          = 0;
    DECLARE @LogMessage     NVARCHAR(MAX) = '';
    DECLARE @DetallesLog    NVARCHAR(MAX) = '';
    DECLARE @FechaInicio    DATETIME      = GETDATE();
    DECLARE @NombreJob      NVARCHAR(128) = '[121_ENT_REPORTOS_MN_ME]   ';

    BEGIN TRY
        IF EXISTS (
            SELECT ID FROM [SILVER].[RR].[121_ENT_REPORTOS_MN_ME]
            WHERE [FECHACONCERTACION] = @FechaSistema
        )
        BEGIN
            DELETE FROM [SILVER].[RR].[121_ENT_REPORTOS_MN_ME]
            WHERE [FECHACONCERTACION] = @FechaSistema;
            SET @FilasEliminadas = @@ROWCOUNT;
            SET @LogMessage = 'Registros eliminados: ' + CAST(@FilasEliminadas AS NVARCHAR(10));
            PRINT @LogMessage;
            SET @DetallesLog = @DetallesLog + @LogMessage + CHAR(13) + CHAR(10);
        END;

        INSERT INTO [RR].[121_ENT_REPORTOS_MN_ME] (
            [FECHACONCERTACION],[HORACONCERTACION],[POSICIONOPERACION],
            [FECHAINICIO],[FECHAVENCIMIENTO],[IMPORTEREPORTO],
            [MONEDAPRECIOUNITARIO],[TASAPREMIO],[TITULOOBJETOREPORTO],
            [PRECIOUNITARIOTITULOS],[NUMEROTITULOSOBJETOREPORTO],
            [CONTRAPARTEREPORTO],[RESIDENCIA_CONTRAPARTE],[PROPIA_TERCEROS],
            [CLIENTE_PROV],[CORROELECTRONICO],[TIPOPOSTURA],[OPERACIONBANCOTRABAJO],
            [HAIRCUT],[REP_SUSTITUCION],[MODALIDAD_REPORTO],[PLAZO_EVERGREEN],
            [REP_CONJUNTO_VAL],[REP_AG_TRIPARTITO],[AGENTE_TRIPARTITO],
            [TASA_REFERENCIA_PREMIO],[SOBRETASA_PREMIO],[PERIODO_PAGO_PREMIO],
            [NUMEROIDENTIFICACIONOPERACION],[CLASIFICACIONCONTABLEOPERACION],
            [FECHAVENCIMIENTO_TITULO],[OFICINA],[EMISION],[SERIE],[TIPOVALOR],
            [SOBRETASA],[EMISOR],[DIASXVENCER_CUPON],[APLICA_ANEXO1C],
            [CUSTODIO],[FECHAVALOR],[CLIENTE],[RESTRICCION]
        )
        SELECT
            R.FECHACONCERTACION,R.HORACONCERTACION,R.POSICIONOPERACION,
            R.FECHAINICIO,R.FECHAVENCIMIENTO,R.IMPORTEREPORTO,
            R.MONEDAPRECIOUNITARIO,R.TASAPREMIO,R.TITULOOBJETOREPORTO,
            R.PRECIOUNITARIOTITULOS,R.NUMEROTITULOSOBJETOREPORTO,
            R.CONTRAPARTEREPORTO,R.RESIDENCIA_CONTRAPARTE,R.PROPIA_TERCEROS,
            R.CLIENTE_PROV,R.CORROELECTRONICO,R.TIPOPOSTURA,R.OPERACIONBANCOTRABAJO,
            R.HAIRCUT,R.REP_SUSTITUCION,R.MODALIDAD_REPORTO,R.PLAZO_EVERGREEN,
            R.REP_CONJUNTO_VAL,R.REP_AG_TRIPARTITO,R.AGENTE_TRIPARTITO,
            R.TASA_REFERENCIA_PREMIO,R.SOBRETASA_PREMIO,R.PERIODO_PAGO_PREMIO,
            R.NUMEROIDENTIFICACIONOPERACION,R.CLASIFICACIONCONTABLEOPERACION,
            R.FECHAVENCIMIENTO_TITULO,R.OFICINA,R.EMISION,R.SERIE,R.TIPOVALOR,
            R.SOBRETASA,R.EMISOR,R.DIASXVENCER_CUPON,R.APLICA_ANEXO1C,
            R.CUSTODIO,R.FECHAVALOR,R.CLIENTE,R.RESTRICCION
        FROM [BRONZE].[LMDA].[FT_REPORTOS] R
        WHERE R.FECHACONCERTACION = @FechaSistema;

        SET @FilasInsertadas = @@ROWCOUNT;
        SET @LogMessage = 'Proceso completado. Filas totales: ' + CAST(@FilasInsertadas AS NVARCHAR(10));
        PRINT @LogMessage;
        SET @DetallesLog = @DetallesLog + @LogMessage + CHAR(13) + CHAR(10);
    END TRY
    BEGIN CATCH
        SET @ExitoEjecucion = 0;
        SET @MensajeError   = ERROR_MESSAGE();
        SET @LogMessage     = 'Error durante la ejecucion: ' + @MensajeError;
        PRINT @LogMessage;
        SET @DetallesLog = @DetallesLog + @LogMessage + CHAR(13) + CHAR(10);
    END CATCH

    IF @ExitoEjecucion = 0 AND @CorreoNotificacion IS NOT NULL AND @PerfilCorreo IS NOT NULL
    BEGIN
        DECLARE @Asunto NVARCHAR(255) = 'ALERTA: Error en ' + ISNULL(@NombreJob, 'Job Desconocido');
        DECLARE @Cuerpo NVARCHAR(MAX) = 'Se ha producido un error durante la ejecucion de.' + @NombreJob + CHAR(13)+CHAR(10)
            + '- Programado por: ' + ISNULL(@ProgramadorJob,'No especificado') + CHAR(13)+CHAR(10)
            + '- Mensaje: ' + @MensajeError + CHAR(13)+CHAR(10) + 'Log:' + CHAR(13)+CHAR(10) + @DetallesLog;
        BEGIN TRY
            EXEC msdb.dbo.sp_send_dbmail
                @profile_name = @PerfilCorreo, @recipients = @CorreoNotificacion,
                @subject = @Asunto, @body = @Cuerpo, @body_format = 'TEXT', @importance = 'High';
        END TRY BEGIN CATCH
            SET @DetallesLog = @DetallesLog + 'Error al enviar alerta: ' + ERROR_MESSAGE() + CHAR(13)+CHAR(10);
        END CATCH
    END

    INSERT INTO dbo.LogSilverDiario
        (FechaEjecucion, FilasInsertadas, EstadoEjecucion, MensajeError, DetallesLog, NombreJob, ProgramadorJob)
    VALUES (@FechaInicio, @FilasInsertadas,
        CASE WHEN @ExitoEjecucion=1 THEN 'Exitoso' ELSE 'Error' END,
        CASE WHEN @ExitoEjecucion=1 THEN NULL ELSE @MensajeError END,
        @DetallesLog, @NombreJob, @ProgramadorJob);
END;
GO
PRINT '>> Restaurado SILVER.dbo.[121_ENT_REPORTOS_MN_ME] (SP original, filtro FECHACONCERTACION).';
GO

/* ----------------------------------------------------------------------------
   03 - ION SP: restaurar original (43 cols, filtro FECHACONCERTACION)
   ---------------------------------------------------------------------------- */
USE [ION];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [dbo].[121_ENT_REPORTOS_MN_ME]
    @FECHA DATE
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    SELECT
        FORMAT(S.FECHACONCERTACION,     'yyyy/MM/dd') AS FECHACONCERTACION,
        S.HORACONCERTACION,
        S.POSICIONOPERACION,
        FORMAT(S.FECHAINICIO,           'yyyy/MM/dd') AS FECHAINICIO,
        FORMAT(S.FECHAVENCIMIENTO,      'yyyy/MM/dd') AS FECHAVENCIMIENTO,
        S.IMPORTEREPORTO,S.MONEDAPRECIOUNITARIO,S.TASAPREMIO,S.TITULOOBJETOREPORTO,
        S.PRECIOUNITARIOTITULOS,S.NUMEROTITULOSOBJETOREPORTO,S.CONTRAPARTEREPORTO,
        S.RESIDENCIA_CONTRAPARTE,S.PROPIA_TERCEROS,S.CLIENTE_PROV,
        S.CORROELECTRONICO,S.TIPOPOSTURA,S.OPERACIONBANCOTRABAJO,S.HAIRCUT,
        S.REP_SUSTITUCION,S.MODALIDAD_REPORTO,S.PLAZO_EVERGREEN,S.REP_CONJUNTO_VAL,
        S.REP_AG_TRIPARTITO,S.AGENTE_TRIPARTITO,S.TASA_REFERENCIA_PREMIO,
        S.SOBRETASA_PREMIO,S.PERIODO_PAGO_PREMIO,S.NUMEROIDENTIFICACIONOPERACION,
        S.CLASIFICACIONCONTABLEOPERACION,
        FORMAT(S.FECHAVENCIMIENTO_TITULO,'yyyy/MM/dd') AS FECHAVENCIMIENTO_TITULO,
        S.OFICINA,S.EMISION,S.SERIE,S.TIPOVALOR,S.SOBRETASA,S.EMISOR,
        S.DIASXVENCER_CUPON,S.APLICA_ANEXO1C,S.CUSTODIO,S.FECHAVALOR,S.CLIENTE,S.RESTRICCION
    FROM [SILVER].[RR].[121_ENT_REPORTOS_MN_ME] S
    WHERE S.FECHACONCERTACION = @FECHA;
END;
GO
PRINT '>> Restaurado ION.dbo.[121_ENT_REPORTOS_MN_ME] (SP original, 43 cols).';
GO
PRINT '>> Rollback 121_ENT_REPORTOS_MN_ME completado.';
GO
