-- ============================================================
-- ROLLBACK  126_ENT_ACLME_CONCEPTOSFIJOS
-- Revierte lo aplicado por el AJUSTE:
--   * Restaura SP SILVER (stub) y SP ION (passthrough) originales
--   * Elimina INDICE 126
--   * Dropea el catalogo de conceptos
--   * Quita las columnas agregadas a SILVER (INSTITUCION, DESCRIPCION, MOVIMIENTOS)
-- NO toca BRONZE.LMDA.ACLME (su columna INSTITUCION pertenece al ajuste 125).
-- ============================================================

-- SP SILVER — restaurar stub original
USE [SILVER]
GO
CREATE OR ALTER PROCEDURE [dbo].[126_ENT_ACLME_CONCEPTOSFIJOS]
    @CorreoNotificacion NVARCHAR(255) = NULL,
    @PerfilCorreo       NVARCHAR(255) = NULL,
    @ProgramadorJob     NVARCHAR(128) = NULL,
    @FechaSistema       DATETIME
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    DECLARE @FechaIni DATE = datefromparts(year(@FechaSistema), month(@FechaSistema), 1);
    DECLARE @FechaFin DATE = Dateadd(month, 1, @FechaIni);
    -- stub original (sin transformacion)
    PRINT 'SP stub 126_ENT_ACLME_CONCEPTOSFIJOS restaurado.';
END;
GO

-- SP ION — restaurar passthrough original
USE [ION]
GO
CREATE OR ALTER PROCEDURE [dbo].[126_ENT_ACLME_CONCEPTOSFIJOS]
    @FECHA DATE
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    SELECT [ID],[FECHA_EXTRACCION],[CONCEPTO],[IMPORTE],[MONEDA],[RESERVAS],[FECHA_INFO]
    FROM [SILVER].[RR].[126_ENT_ACLME_CONCEPTOSFIJOS]
    WHERE [FECHA_INFO] = @FECHA;
END;
GO

-- INDICE_REPORTES
USE [ION]
GO
DELETE FROM [dbo].[INDICE_REPORTES] WHERE [numero] = 126;
GO

-- Catalogo de conceptos
USE [BRONZE]
GO
IF OBJECT_ID('[RR].[CATALOGO_CONCEPTOS_PLAZO_FIJO_ACLME]', 'U') IS NOT NULL
    DROP TABLE [RR].[CATALOGO_CONCEPTOS_PLAZO_FIJO_ACLME];
GO

-- Columnas agregadas a SILVER
USE [SILVER]
GO
IF OBJECT_ID('[DF_RR_126_CF_INSTITUCION]', 'D') IS NOT NULL
    ALTER TABLE [RR].[126_ENT_ACLME_CONCEPTOSFIJOS] DROP CONSTRAINT [DF_RR_126_CF_INSTITUCION];
IF COL_LENGTH('RR.126_ENT_ACLME_CONCEPTOSFIJOS','INSTITUCION') IS NOT NULL
    ALTER TABLE [RR].[126_ENT_ACLME_CONCEPTOSFIJOS] DROP COLUMN [INSTITUCION];
IF COL_LENGTH('RR.126_ENT_ACLME_CONCEPTOSFIJOS','DESCRIPCION') IS NOT NULL
    ALTER TABLE [RR].[126_ENT_ACLME_CONCEPTOSFIJOS] DROP COLUMN [DESCRIPCION];
IF COL_LENGTH('RR.126_ENT_ACLME_CONCEPTOSFIJOS','MOVIMIENTOS') IS NOT NULL
    ALTER TABLE [RR].[126_ENT_ACLME_CONCEPTOSFIJOS] DROP COLUMN [MOVIMIENTOS];
GO
