-- 9725
-- Suma de todas las compras de spots
SELECT CAST(SUM([MONTO] / NULLIF([TIPO_CAMBIO], 0)) AS DECIMAL(15, 8)) AS COMPRA_SPOTS
SELECT SUM(MONTO) as COMPRA_SPOTS
FROM [BRONZE].[LMDA].[ACLME]
WHERE TIPO_OPERACION IN ('SW', 'FX') AND MONEDA = 'USD' AND MONEDA_MXN = 'MXN';
-- 9890
-- Suma de todas las Compras de Forwards.
SELECT CAST(SUM([MONTO] / NULLIF([TIPO_CAMBIO], 0)) AS DECIMAL(18, 8))  AS COMPRA_FORWRDS
--SELECT *
FROM [BRONZE].[LMDA].[ACLME]
WHERE TIPO_OPERACION = 'FW' AND MONEDA = 'USD' AND MONEDA_MXN = 'MXN';
-- 9730
-- Suma de todas las Ventas de Spots 
SELECT SUM([MONTO]) AS VENTA_SPOTS
FROM [BRONZE].[LMDA].[ACLME]
WHERE TIPO_OPERACION = 'FX' AND MONEDA = 'MXN' AND MONEDA_MXN = 'USD';
-- 9900
-- Suma de todas las Venta de Forwards.
SELECT SUM([MONTO]) AS VENTA_FORWRDS
FROM [BRONZE].[LMDA].[ACLME]
WHERE TIPO_OPERACION = 'FW' AND MONEDA = 'MXN' AND MONEDA_MXN = 'USD';


SELECT 
    C.CONCEPTO,
    C.OPERACION,
    CAST(SUM(A.[MONTO]) AS DECIMAL(38, 8)) AS TOTAL
FROM [BRONZE].[LMDA].[ACLME] A
INNER JOIN [BRONZE].[RR].[CAT_ACLME_CONCEPTOS_FIJOS] C
    ON A.TIPO_OPERACION = C.TIPO_OPERACION
   AND A.MONEDA = C.MONEDA
   AND A.MONEDA_MXN = C.MONEDA_MXN
GROUP BY 
    C.CONCEPTO,
    C.OPERACION
ORDER BY 
    C.CONCEPTO;



-- CATALOGO CONCEPTOS FIJOS
-- 1. Eliminar la tabla si ya existe para evitar errores en re-ejecuciones
IF OBJECT_ID('[BRONZE].[RR].[CAT_ACLME_CONCEPTOS_FIJOS]', 'U') IS NOT NULL
    DROP TABLE [BRONZE].[RR].[CAT_ACLME_CONCEPTOS_FIJOS];
GO

-- 2. Creación de la tabla (sin la columna CALCULO)
CREATE TABLE [BRONZE].[RR].[CAT_ACLME_CONCEPTOS_FIJOS] (
    [CONCEPTO]        INT NOT NULL,          -- Ej. 9725, 9890
    [OPERACION]       VARCHAR(50) NOT NULL,  -- Ej. 'COMPRA_SPOTS'
    [TIPO_OPERACION]  VARCHAR(10) NOT NULL,  -- 'SW', 'FX', 'FW'
    [MONEDA]          VARCHAR(10) NOT NULL,  -- 'USD', 'MXN'
    [MONEDA_MXN]      VARCHAR(10) NOT NULL   -- 'MXN', 'USD'
);
GO

-- 3. Inserción de los datos catalogados
INSERT INTO [BRONZE].[RR].[CAT_ACLME_CONCEPTOS_FIJOS] 
    ([CONCEPTO], [OPERACION], [TIPO_OPERACION], [MONEDA], [MONEDA_MXN])
VALUES 
    -- 9725: COMPRA_SPOTS (Abarca 'SW' y 'FX')
    (9725, 'COMPRA_SPOTS',   'SW', 'USD', 'MXN'),
    (9725, 'COMPRA_SPOTS',   'FX', 'USD', 'MXN'),

    -- 9890: COMPRA_FORWRDS (Abarca 'FW')
    (9890, 'COMPRA_FORWRDS', 'FW', 'USD', 'MXN'),

    -- 9730: VENTA_SPOTS (Abarca 'FX')
    (9730, 'VENTA_SPOTS',    'FX', 'MXN', 'USD'),

    -- 9900: VENTA_FORWRDS (Abarca 'FW')
    (9900, 'VENTA_FORWRDS',  'FW', 'MXN', 'USD');
GO