-- ============================================================
-- ROLLBACK  075_ENT_TENENCIA_REPAD
-- ============================================================

-- ============================================================
-- SECTION R01 | Restaurar SP ION (version original con bugs)
-- ============================================================
USE [ION]
GO

CREATE OR ALTER PROCEDURE [dbo].[075_ENT_TENENCIA_REPAD]
    @FECHA DATE
AS
BEGIN
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
    DECLARE @FechaIni DATE, @FechaFin DATE

    SET @FechaIni = DATEADD(DAY, -(DATEPART(WEEKDAY, '20250203') + 5) % 7, '20250203')
    SET @FechaFin = DATEADD(DAY, 7, @FechaIni)

    SELECT
        ID,
        FECHA_EXTRACCION,
        TituloObjeto,
        NumeroTitulos,
        Contraparte,
        Moneda,
        PrecioUnitario,
        PrecioValMercado,
        ClasificacionContable,
        PosicionOperacion,
        CveTipoInstrumento,
        Oficina,
        DepositadoEnGarantia,
        FECHA_EXTRACCION AS FECHA_REPORTE
    FROM [SILVER].[RR].[075_ENT_TENENCIA_REPAD]
    WHERE [FECHA_EXTRACCION] >= @FechaIni AND [FECHA_EXTRACCION] < @FechaFin;
END;
GO

-- ============================================================
-- SECTION R02 | Eliminar SP SILVER (no existia antes del ajuste)
-- ============================================================
USE [SILVER]
GO

IF OBJECT_ID('dbo.[075_ENT_TENENCIA_REPAD]', 'P') IS NOT NULL
    DROP PROCEDURE [dbo].[075_ENT_TENENCIA_REPAD];
GO

-- ============================================================
-- SECTION R03 | Revertir sp_rename en SILVER (UPPERCASE -> camelCase)
-- ============================================================
USE [SILVER]
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='TITULOOBJETO')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].TITULOOBJETO',          'TituloObjeto',          'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='NUMEROTITULOS')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].NUMEROTITULOS',          'NumeroTitulos',          'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='CONTRAPARTE')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].CONTRAPARTE',            'Contraparte',            'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='MONEDA')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].MONEDA',                 'Moneda',                 'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='PRECIOUNITARIO')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].PRECIOUNITARIO',         'PrecioUnitario',         'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='PRECIO_VAL_MERCADO')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].PRECIO_VAL_MERCADO',     'PrecioValMercado',       'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='CLASIFICACIONCONTABLE')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].CLASIFICACIONCONTABLE',  'ClasificacionContable',  'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='POSICIONOPERACION')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].POSICIONOPERACION',      'PosicionOperacion',      'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='CVETIPOINSTRUMENTO')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].CVETIPOINSTRUMENTO',     'CveTipoInstrumento',     'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='OFICINA')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].OFICINA',                'Oficina',                'COLUMN';
GO
USE [SILVER]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RR' AND TABLE_NAME='075_ENT_TENENCIA_REPAD' AND COLUMN_NAME='DEPOSITADOENGARANTIA')
    EXEC sp_rename 'RR.[075_ENT_TENENCIA_REPAD].DEPOSITADOENGARANTIA',   'DepositadoEnGarantia',   'COLUMN';
GO

-- ============================================================
-- SECTION R04 | Revertir sp_rename en BRONZE (UPPERCASE -> camelCase)
-- ============================================================
USE [BRONZE]
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='TITULOOBJETO')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].TITULOOBJETO',          'TituloObjeto',          'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='NUMEROTITULOS')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].NUMEROTITULOS',          'NumeroTitulos',          'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='CONTRAPARTE')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].CONTRAPARTE',            'Contraparte',            'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='MONEDA')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].MONEDA',                 'Moneda',                 'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='PRECIOUNITARIO')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].PRECIOUNITARIO',         'PrecioUnitario',         'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='PRECIO_VAL_MERCADO')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].PRECIO_VAL_MERCADO',     'PrecioValMercado',       'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='CLASIFICACIONCONTABLE')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].CLASIFICACIONCONTABLE',  'ClasificacionContable',  'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='POSICIONOPERACION')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].POSICIONOPERACION',      'PosicionOperacion',      'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='CVETIPOINSTRUMENTO')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].CVETIPOINSTRUMENTO',     'CveTipoInstrumento',     'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='OFICINA')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].OFICINA',                'Oficina',                'COLUMN';
GO
USE [BRONZE]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='LMDA' AND TABLE_NAME='FT_TENENCIA' AND COLUMN_NAME='DEPOSITADOENGARANTIA')
    EXEC sp_rename 'LMDA.[FT_TENENCIA].DEPOSITADOENGARANTIA',   'DepositadoEnGarantia',   'COLUMN';
GO

-- ============================================================
-- SECTION R05 | INDICE_REPORTES — restaurar frecuencia original
-- ============================================================
USE [ION]
GO

UPDATE [dbo].[INDICE_REPORTES]
SET [frecuencia] = 'Solo cuando hay nuevas contrapartes'
WHERE [numero] = 75;
GO
